<?php

declare(strict_types=1);

namespace CryptoChief\Processing\Tests;

use CryptoChief\Processing\Exception\CryptoChiefException;
use CryptoChief\Processing\Sign;
use CryptoChief\Processing\Tests\Support\GatewayHmacV1;
use CryptoChief\Processing\Tests\Support\Vectors;
use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\TestCase;

/**
 * Request HMAC v1 vectors from tests/testdata/hmac_v1_vectors.json (generated by the
 * gateway).
 *
 * Every record is signed and verified. The verifying side sees `Merchant`, `X-CC-Timestamp`,
 * `X-CC-Nonce`, `X-CC-Signature` = `v1=<signature>`, `Idempotency-Key` when the record has
 * one and `Content-Type: application/json` when the body is not empty; `headers` replaces
 * the listed ones (a list of values: `[]` absent, `[""]` empty, two values repeated).
 */
final class HmacV1Test extends TestCase
{
    private const EXPECT = [
        'ok' => GatewayHmacV1::OK,
        'bad_auth_headers' => GatewayHmacV1::BAD_AUTH_HEADERS,
        'timestamp_out_of_range' => GatewayHmacV1::TIMESTAMP_OUT_OF_RANGE,
        'invalid_signature' => GatewayHmacV1::INVALID_SIGNATURE,
    ];

    /**
     * @return array<string, array{array<string, mixed>}>
     */
    public static function vectors(): array
    {
        $out = [];
        foreach (Vectors::request() as $record) {
            $out[(string) $record['name']] = [$record];
        }

        return $out;
    }

    public function testVectorFileIsTheReferenceCopy(): void
    {
        $raw = Vectors::raw(Vectors::REQUEST_FILE);

        self::assertSame(Vectors::REQUEST_SHA256, hash('sha256', $raw));
        self::assertStringNotContainsString("\r", $raw);
    }

    public function testVectorSetShape(): void
    {
        $counts = [];
        foreach (Vectors::request() as $record) {
            $counts[$record['expect']] = ($counts[$record['expect']] ?? 0) + 1;
        }
        ksort($counts);

        self::assertSame(
            ['bad_auth_headers' => 24, 'invalid_signature' => 3, 'ok' => 21, 'timestamp_out_of_range' => 2],
            $counts,
        );
    }

    /**
     * The signing side: string to sign and signature, in records with a refusal too.
     *
     * @param array<string, mixed> $v
     */
    #[DataProvider('vectors')]
    public function testStringToSignAndSignature(array $v): void
    {
        self::assertSame($v['body_sha256'], Sign::hmacV1BodySha256($v['body']));

        self::assertSame($v['string_to_sign'], Sign::hmacV1StringToSign(
            timestamp: $v['timestamp'],
            nonce: $v['nonce'],
            method: $v['method'],
            path: $v['path'],
            query: $v['query'],
            merchant: $v['merchant'],
            idempotencyKey: $v['idempotency_key'],
            body: $v['body'],
        ));

        self::assertSame($v['signature'], Sign::hmacV1Sign(
            apiKey: $v['api_key'],
            timestamp: $v['timestamp'],
            nonce: $v['nonce'],
            method: $v['method'],
            path: $v['path'],
            query: $v['query'],
            merchant: $v['merchant'],
            idempotencyKey: $v['idempotency_key'],
            body: $v['body'],
        ));
    }

    /**
     * The verifying side: exactly the expected outcome.
     *
     * @param array<string, mixed> $v
     */
    #[DataProvider('vectors')]
    public function testVerify(array $v): void
    {
        self::assertArrayHasKey($v['expect'], self::EXPECT);

        self::assertSame(self::EXPECT[$v['expect']], self::check($v, $v['now'])->outcome, $v['name']);
    }

    /**
     * A record with a refusal carries exactly one defect: without the header overrides and
     * with the verifier's clock at the record's timestamp, the same record passes.
     *
     * @param array<string, mixed> $v
     */
    #[DataProvider('vectors')]
    public function testSingleDefect(array $v): void
    {
        $clean = $v;
        if ($v['expect'] !== 'ok') {
            unset($clean['headers']);
        }

        self::assertSame(GatewayHmacV1::OK, self::check($clean, (int) $v['timestamp'])->outcome, $v['name']);
    }

    public function testStringToSignLayout(): void
    {
        $merchant = '3f2a1b4c-5d6e-7f80-9a1b-2c3d4e5f6071';
        $sts = Sign::hmacV1StringToSign(
            timestamp: '1789430400',
            nonce: '0123456789abcdef0123456789abcdef',
            method: 'post',
            path: '/v1/credits/balance',
            query: '',
            merchant: $merchant,
            idempotencyKey: '',
            body: '',
        );

        self::assertSame(
            "CC-HMAC-SHA256-REQ-V1\n"
            . "1789430400\n"
            . "0123456789abcdef0123456789abcdef\n"
            . "POST\n"
            . "/v1/credits/balance\n"
            . "\n"
            . $merchant . "\n"
            . "\n"
            . 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
            $sts,
        );
    }

    /**
     * Only `a`-`z` are raised: an RFC 9110 token is ASCII, and a Unicode mapping would
     * rewrite bytes (i -> I, µ -> Μ, full-width letters) the server keeps as they are.
     */
    public function testMethodUppercaseIsAsciiOnly(): void
    {
        $ascii = ['post' => 'POST', 'POST' => 'POST', 'PoSt' => 'POST', 'get' => 'GET', 'delete' => 'DELETE'];
        foreach ($ascii as $method => $want) {
            self::assertSame($want, Sign::upperMethod($method));
            self::assertSame($want, self::methodField($method));
        }

        $nonAscii = [
            "p\u{0131}st" => "P\u{0131}ST",   // dotless i stays, a-z around it rises
            "p\u{00B5}st" => "P\u{00B5}ST",   // micro sign is not mapped to capital mu
            "\u{FF30}ost" => "\u{FF30}OST",   // full-width P stays
            "gét" => "GéT",
            "\u{43C}ethod" => "\u{43C}ETHOD",
        ];
        foreach ($nonAscii as $method => $want) {
            self::assertSame($want, Sign::upperMethod($method), $method);
            self::assertSame($want, self::methodField($method), $method);
        }
    }

    /**
     * The path is signed percent-decoded and the query raw, both in the verified vectors and
     * in a request carrying %2F, %20 and non-ASCII.
     */
    public function testPathIsDecodedAndQueryIsRaw(): void
    {
        $path = '/v1/orders/payout%2F8814/a%20b/%D0%BA%D0%BB';
        $query = 'q=a%20b&n=%D0%BA%D0%BB&raw=a+b';

        $sts = Sign::hmacV1StringToSign(
            timestamp: '1789430400',
            nonce: '0123456789abcdef0123456789abcdef',
            method: 'POST',
            path: rawurldecode($path),
            query: $query,
            merchant: 'M',
            idempotencyKey: '',
            body: '',
        );
        $lines = explode("\n", $sts);

        self::assertSame("/v1/orders/payout/8814/a b/\u{43A}\u{43B}", $lines[4]);
        self::assertSame($query, $lines[5]);
    }

    public function testBlankApiKeyIsRefused(): void
    {
        $record = Vectors::request()[0];

        foreach (['', ' ', "\t", " \t "] as $apiKey) {
            try {
                Sign::hmacV1Sign($apiKey, '1789430400', 'nonce_0123456789', 'POST', '/v1/x', '', 'M', '', '');
                self::fail('expected CryptoChiefException');
            } catch (CryptoChiefException $e) {
                self::assertStringContainsString('api_key is required', $e->getMessage());
            }

            self::assertTrue(Sign::isBlankApiKey($apiKey));
            self::assertSame(
                GatewayHmacV1::INVALID_SIGNATURE,
                self::check($record, (int) $record['timestamp'], $apiKey)->outcome,
            );
        }

        self::assertFalse(Sign::isBlankApiKey(' k '));
    }

    public function testLineBreakInFieldThrows(): void
    {
        foreach (["a\nb", "a\rb"] as $bad) {
            try {
                Sign::hmacV1StringToSign('1789430400', $bad, 'POST', '/v1/x', '', 'M', '', '');
                self::fail('expected CryptoChiefException');
            } catch (CryptoChiefException $e) {
                self::assertStringContainsString('CR or LF', $e->getMessage());
            }
        }
    }

    public function testBodyWithLineBreaksIsAllowed(): void
    {
        $sts = Sign::hmacV1StringToSign('1789430400', 'nonce', 'POST', '/v1/x', '', 'M', '', "{\n}");

        self::assertStringEndsWith("\n" . hash('sha256', "{\n}"), $sts);
    }

    public function testNonceFormat(): void
    {
        $a = Sign::hmacV1Nonce();
        $b = Sign::hmacV1Nonce();

        self::assertMatchesRegularExpression('/^[0-9a-f]{32}$/', $a);
        self::assertNotSame($a, $b);
    }

    /** The METHOD line of the string to sign. */
    private static function methodField(string $method): string
    {
        $sts = Sign::hmacV1StringToSign('1789430400', 'nonce', $method, '/v1/x', '', 'M', '', '');
        $lines = explode("\n", $sts);
        self::assertCount(9, $lines);

        return $lines[3];
    }

    /**
     * @param array<string, mixed> $v
     */
    private static function check(array $v, int $now, ?string $apiKey = null): GatewayHmacV1
    {
        return GatewayHmacV1::check(
            apiKey: $apiKey ?? (string) $v['api_key'],
            method: (string) $v['method'],
            path: (string) $v['path'],
            query: (string) $v['query'],
            headers: self::headers($v),
            body: (string) $v['body'],
            now: $now,
        );
    }

    /**
     * @param array<string, mixed> $v
     * @return array<string, list<string>>
     */
    private static function headers(array $v): array
    {
        $headers = [
            'merchant' => [(string) $v['merchant']],
            'x-cc-timestamp' => [(string) $v['timestamp']],
            'x-cc-nonce' => [(string) $v['nonce']],
            'x-cc-signature' => [Sign::HMAC_V1_PREFIX . $v['signature']],
        ];
        if ($v['idempotency_key'] !== '') {
            $headers['idempotency-key'] = [(string) $v['idempotency_key']];
        }
        if ($v['body'] !== '') {
            $headers['content-type'] = ['application/json'];
        }
        foreach ($v['headers'] ?? [] as $name => $values) {
            $headers[strtolower((string) $name)] = array_values($values);
        }

        return $headers;
    }
}
