<?php

declare(strict_types=1);

namespace CryptoChief\Processing\Tests;

use CryptoChief\Processing\Exception\WebhookHeadersException;
use CryptoChief\Processing\Exception\WebhookSignatureException;
use CryptoChief\Processing\Exception\WebhookTimestampException;
use CryptoChief\Processing\Exception\WebhookVerificationException;
use CryptoChief\Processing\Sign;
use CryptoChief\Processing\Tests\Support\Vectors;
use CryptoChief\Processing\Webhook;
use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\TestCase;

/**
 * Webhook HMAC v1 vectors from tests/testdata/webhook_hmac_v1_vectors.json (generated by the
 * webhook service).
 *
 * Headers a receiver sees: X-CC-Timestamp = timestamp, X-Webhook-Delivery = delivery_id,
 * X-CC-Signature = signature; `headers` replaces the listed ones (a list of values: `[]`
 * absent, two values repeated).
 */
final class WebhookV1VectorsTest extends TestCase
{
    private const TOLERANCE = 300;

    private const EXPECT = [
        'ok' => null,
        'bad_headers' => WebhookHeadersException::class,
        'timestamp_out_of_range' => WebhookTimestampException::class,
        'bad_signature' => WebhookSignatureException::class,
    ];

    /**
     * @return array<string, array{array<string, mixed>}>
     */
    public static function vectors(): array
    {
        $out = [];
        foreach (Vectors::webhook() as $record) {
            $out[(string) $record['name']] = [$record];
        }

        return $out;
    }

    public function testVectorFileIsTheReferenceCopy(): void
    {
        $raw = Vectors::raw(Vectors::WEBHOOK_FILE);

        self::assertSame(Vectors::WEBHOOK_SHA256, hash('sha256', $raw));
        self::assertStringNotContainsString("\r", $raw);
    }

    public function testVectorSetShape(): void
    {
        $counts = [];
        foreach (Vectors::webhook() as $record) {
            $counts[$record['expect']] = ($counts[$record['expect']] ?? 0) + 1;
        }
        ksort($counts);

        self::assertSame(
            ['bad_headers' => 26, 'bad_signature' => 4, 'ok' => 22, 'timestamp_out_of_range' => 2],
            $counts,
        );
    }

    /**
     * @param array<string, mixed> $v
     */
    #[DataProvider('vectors')]
    public function testStringToSignAndSignature(array $v): void
    {
        $body = self::body($v);

        self::assertSame($v['body_sha256'], hash('sha256', $body));
        self::assertSame($v['string_to_sign'], Sign::webhookV1StringToSign($v['timestamp'], $v['delivery_id'], $body));
        self::assertSame($v['signature'], Sign::webhookV1Sign($v['api_key'], $v['timestamp'], $v['delivery_id'], $body));
    }

    /**
     * @param array<string, mixed> $v
     */
    #[DataProvider('vectors')]
    public function testVerify(array $v): void
    {
        self::assertVerifyOutcome($v, self::headers($v));
    }

    /**
     * The same outcome with the header names lowercased and single values passed as strings.
     *
     * @param array<string, mixed> $v
     */
    #[DataProvider('vectors')]
    public function testVerifyLowercaseStringHeaders(array $v): void
    {
        $headers = [];
        foreach (self::headers($v) as $name => $values) {
            $headers[strtolower($name)] = count($values) === 1 ? $values[0] : $values;
        }

        self::assertVerifyOutcome($v, $headers);
    }

    /**
     * The same outcome through Webhook::headersFromGlobals(), for records whose headers each
     * have at most one value (`$_SERVER` cannot carry a repeated header).
     *
     * @param array<string, mixed> $v
     */
    #[DataProvider('vectors')]
    public function testVerifyHeadersFromGlobals(array $v): void
    {
        $server = ['REQUEST_METHOD' => 'POST', 'CONTENT_TYPE' => 'application/json'];
        foreach (self::headers($v) as $name => $values) {
            if (count($values) > 1) {
                self::assertSame('bad_headers', $v['expect']);
                return;
            }
            if ($values !== []) {
                $server['HTTP_' . strtoupper(str_replace('-', '_', $name))] = $values[0];
            }
        }

        self::assertVerifyOutcome($v, Webhook::headersFromGlobals($server));
    }

    /**
     * @param array<string, mixed> $v
     * @param array<string, mixed> $headers
     */
    private static function assertVerifyOutcome(array $v, array $headers): void
    {
        self::assertArrayHasKey($v['expect'], self::EXPECT);
        $expected = self::EXPECT[$v['expect']];

        try {
            Webhook::verify($v['api_key'], self::body($v), $headers, self::TOLERANCE, $v['now']);
            $thrown = null;
        } catch (WebhookVerificationException $e) {
            $thrown = $e::class;
        }

        self::assertSame($expected, $thrown, $v['name']);
    }

    /**
     * @param array<string, mixed> $v
     */
    private static function body(array $v): string
    {
        if (array_key_exists('body_base64', $v)) {
            $body = base64_decode((string) $v['body_base64'], true);
            self::assertIsString($body);

            return $body;
        }

        return (string) $v['body'];
    }

    /**
     * @param array<string, mixed> $v
     * @return array<string, list<string>>
     */
    private static function headers(array $v): array
    {
        $headers = [
            Webhook::TIMESTAMP_HEADER => [(string) $v['timestamp']],
            Webhook::DELIVERY_HEADER => [(string) $v['delivery_id']],
            Webhook::SIGNATURE_HEADER => [(string) $v['signature']],
        ];
        foreach ($v['headers'] ?? [] as $name => $values) {
            $headers[$name] = array_values($values);
        }

        return $headers;
    }
}
